title: Erin Sylve's Professional Portfolio
description: Hi! I'm a graduating industrial and systems engineer of the Texas A&M class of 2021. Feel free to use this page to learn more about me!
show_downloads: "true"